// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Kedh2f2Yb8HJdA5oRG6umbsOXRgqEBs',
    appId: '1:644207825645:web:5f0ca55b528890fc6db2e4',
    messagingSenderId: '644207825645',
    projectId: 'deesporapa',
    authDomain: 'deesporapa.firebaseapp.com',
    storageBucket: 'deesporapa.firebasestorage.app',
    measurementId: 'G-8NZ1QLH6PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmRbcARGhNbJ-zmknfnqTtC-dGkM7gyw',
    appId: '1:644207825645:android:b05fc743fbea34cd6db2e4',
    messagingSenderId: '644207825645',
    projectId: 'deesporapa',
    storageBucket: 'deesporapa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdBLdojWY34Khrg350nk13pkNl25aUcZw',
    appId: '1:644207825645:ios:0d10d179741183816db2e4',
    messagingSenderId: '644207825645',
    projectId: 'deesporapa',
    storageBucket: 'deesporapa.firebasestorage.app',
    iosBundleId: 'com.example.deespora',
  );
}
